#!/bin/bash
DATE=$1
if [ -z "$1" ]; then
  DATE=`date "+%Y-%m-%d"`
fi

git log --author=`git config --global user.name` --after="$DATE 0:0" --before="`date -v+1d -j -f "%Y-%m-%d" "$DATE" "+%Y-%m-%d"` 0:0" --branches *
